limcr-dev/daon

craco.config.js, front-react/package-lock.json, package-lock.json
=> cracoConfig add

front-react/src/pages/SignUp/SignUp.js, src/main/java/com/spring/daon/controller/LoginController.java
=> login init real complete

README.md, front-react/README.md
=> readme update

front-react/package-lock.json, front-react/package.json
=> fontawesome module install

front-react/src/App.js, front-react/src/approve/ApproveRouter.js, front-react/src/attendMgt/AttendRouter.js, front-react/src/attendMgt/components/AttendMgtTree.js, front-react/src/attendMgt/css/AttendMgtTree.css, front-react/src/attendMgt/css/DatePicker.css, front-react/src/attendMgt/css/MyCalendar.css, front-react/src/attendMgt/css/attendMgtMain.css, front-react/src/attendMgt/pages/AttendMgtLeftbar.js, front-react/src/attendMgt/pages/MyCalendar.js, front-react/src/attendMgt/pages/VacationHistory.js, front-react/src/common/pages/Leftbar.js, front-react/src/hrMgt/HrMgtRouter.js, front-react/src/mail/MailRouter.js, front-react/src/messenger/MessengerRouter.js, front-react/src/orgChart/OrgChartRouter.js, front-react/src/performMgt/PerformMgtRouter.js, front-react/src/schedule/ScheduleRouter.js, front-react/src/schedule/css/DatePicker.css, front-react/src/schedule/css/MyCalendar.css, front-react/src/schedule/pages/MyCalendar.js, front-react/src/schedule/pages/Schedule.js, front-react/src/schedule/pages/Scroll.js, front-react/src/schedule/pages/Test.js, src/main/java/com/spring/daon/attendMgt/AttendMgtController.java, src/main/java/com/spring/daon/attendMgt/AttendMgtServiceImpl.java, src/main/java/com/spring/daon/attendMgt/Attendance.java
router 파일 생성 
app.js 수정
근태관리 메인 페이지 프론트만 거의 완성
=> router change simple attend 10%

src/main/java/com/spring/daon/hrMgt/Employees.java
=> employeesDTO edit

front-react/src/approve/components/ApproveMenu.js, front-react/src/approve/css/approve.css, front-react/src/approve/pages/Approve.js, front-react/src/approve/pages/ApproveLeftbar.js, front-react/src/approve/pages/ApproveList.js
=> repository setting

front-react/src/App.js, front-react/src/attendMgt/AttendRouter.js, front-react/src/common/pages/Leftbar.js, front-react/src/hrMgt/HrMgtRouter.js, front-react/src/library/BoardRouter.js, front-react/src/library/components/BoardMenu.js, front-react/src/library/css/board.css, front-react/src/library/pages/BaordLeftbar.js, front-react/src/library/pages/Board.js, front-react/src/library/pages/NoticeList.js, front-react/src/mail/MailRouter.js, front-react/src/messenger/MessengerRouter.js, front-react/src/orgChart/OrgChartRouter.js, front-react/src/performMgt/PerformMgtRouter.js, front-react/src/schedule/ScheduleRouter.js, src/main/resources/application.properties
**router error 해결**
App.js와 Router.js 분리하면서 f12창에서 다음과 같은 오류 발생
_No routes matched location "/board"_
해결방법
1. App.js router 수정
```
function App() {
return (
<BrowserRouter>
<Routes>
{/* 기본 경로 라우트 */}
<Route path="/" element={<Login />} />
<Route path="/home" element={<Home />} />
{/* 서브 라우트들 */}
<Route path="/approve/*" element={<ApproveRouter />} />
<Route path="/attendMgt/*" element={<AttendRouter />} />
<Route path="/hrMgt/*" element={<HrMgtRouter />} />
<Route path="/mail/*" element={<MailRouter />} />
<Route path="/messenger/*" element={<MessengerRouter />} />
<Route path="/orgChart/*" element={<OrgChartRouter />} />
<Route path="/performMgt/*" element={<PerformMgtRouter />} />
<Route path="/schedule/*" element={<ScheduleRouter />} />
<Route path="/board/*" element={<BoardRouter />} …
```
=> router error resolve

front-react/package-lock.json, front-react/src/approve/ApproveRouter.js, front-react/src/approve/pages/Approve.js, front-react/src/approve/pages/ApproveLeftbar.js, front-react/src/library/BoardRouter.js, front-react/src/library/components/BoardMenu.js, front-react/src/library/css/board.css, front-react/src/library/pages/Board.js, front-react/src/library/pages/BoardLeftbar.js, front-react/src/library/pages/InsertNotice.js, front-react/src/library/pages/NoticeDetail.js, front-react/src/library/pages/NoticeList.js, front-react/src/library/pages/UpdateNotice.js, src/main/java/com/spring/daon/board/BoardController.java, src/main/java/com/spring/daon/board/BoardMapper.java, src/main/java/com/spring/daon/board/BoardServiceImpl.java, src/main/java/com/spring/daon/board/Notice.java, src/main/resources/application.properties, src/main/resources/mappers/boardMapper.xml
**게시판 - 공지사항 기능 및 화면 구현**
1. 목록 조회
2. 공지 작성
3. 상세 페이지
4. 공지 수정
5. 공지 삭제
_- 로그인 기능 미완료로 emp_no 직접 입력하는 방법으로 구현, 로그인 기능 완성되면 수정할 예정_
=> notice complete(emp_no hard coding)

front-react/src/library/pages/InsertNotice.js, front-react/src/library/pages/UpdateNotice.js
=> 공지수정 에러 해결

README.md, front-react/package-lock.json, front-react/package.json, front-react/src/attendMgt/AttendRouter.js, front-react/src/attendMgt/components/AttendMgtTree.js, front-react/src/attendMgt/css/AttendCalendar.css, front-react/src/attendMgt/css/DeptStatus.css, front-react/src/attendMgt/pages/AttendFooter.js, front-react/src/attendMgt/pages/AttendMgt.js, front-react/src/attendMgt/pages/AttendMgtLeftbar.js, front-react/src/attendMgt/pages/DeptStatus.js, front-react/src/attendMgt/pages/History.js, front-react/src/attendMgt/pages/MoveDateHeader.js, front-react/src/attendMgt/pages/VacationFooter.js, front-react/src/attendMgt/pages/VacationMain.js, src/main/java/com/spring/daon/attendMgt/AttendMgtController.java, src/main/resources/mappers/attendanceMapper.xml
colorPicker 추가
엥 원하지 않은 중간백업까지 올라가버렸네
=> Topic jjs8

front-react/package-lock.json, front-react/package.json
jwt-decode 설치해서 package.json 업로드합니다.
=> install jwt-decode

front-react/src/performMgt/css/CompList.css, front-react/src/performMgt/pages/sub/TestList.js
=> complist.css update

front-react/src/common/pages/Header.js
=> logout errer resolve

front-react/src/attendMgt/pages/AttendMgt.js, front-react/src/attendMgt/pages/AttendMgtLeftbar.js, front-react/src/attendMgt/pages/History.js, front-react/src/attendMgt/pages/VacationMain.js, front-react/src/schedule/pages/Schedule.js, front-react/src/schedule/pages/ScheduleLeftbar.js, src/main/java/com/spring/daon/attendMgt/AttendMgtController.java
근태관리 leftbar에서 출퇴근 버튼을 아직 클릭 안할 시(출퇴근 기록 X) 데이터가 없는데 json형태로 바꿀 수 없다고 console 에 오류 뜨는걸 컨트롤러에서 데이터가 없을 시 임의 값을 전달로 해결
if (result == null) {
return ResponseEntity.ok(Collections.emptyMap());
}
else {
return new ResponseEntity<>(result, HttpStatus.OK);
}
각 페이지에 토큰user값 적용시킴 하드코딩 XX
=> error edit

front-react/src/approve/css/commonForm.css, front-react/src/approve/css/vacationForm.css, front-react/src/approve/css/workReportForm.css, front-react/src/approve/pages/Approve.js, front-react/src/approve/pages/ApproveForm.js, front-react/src/approve/pages/SelectForm.js, front-react/src/approve/pages/VacationForm.js, front-react/src/approve/pages/WorkReportForm.js, src/main/java/com/spring/daon/approve/ApproveController.java, src/main/java/com/spring/daon/approve/ApproveMapper.java, src/main/java/com/spring/daon/approve/ApproveService.java, src/main/java/com/spring/daon/approve/ApproveServiceImpl.java, src/main/java/com/spring/daon/approve/Documents.java, src/main/resources/mappers/approveMapper.xml
전자결재 하는 중
- 메인에서 진행중, 완료 리스트 조회
- form 만드는 중
=> approve 10%

src/main/java/com/spring/daon/hrMgt/Employees.java
=> employeesDTO timezone add

src/main/java/com/spring/daon/login/config/SecurityConfig.java
=> SecurityConfig +messenger

front-react/src/performMgt/PerformMgtRouter.js, front-react/src/performMgt/components/EvalTree.js, front-react/src/performMgt/css/CompList.css, front-react/src/performMgt/pages/CheckComp.js, front-react/src/performMgt/pages/EvalList.js, front-react/src/performMgt/pages/EvalPeerQue.js, front-react/src/performMgt/pages/EvalQue.js, front-react/src/performMgt/pages/EvalSelQue.js, front-react/src/performMgt/pages/sub/QuesList.js, front-react/src/performMgt/pages/sub/TestList.js, src/main/java/com/spring/daon/performMgt/EvalPeer.java, src/main/java/com/spring/daon/performMgt/PerformMgtController.java, src/main/java/com/spring/daon/performMgt/PerformMgtMapper.java, src/main/java/com/spring/daon/performMgt/PerformMgtServiceImpl.java, src/main/java/com/spring/daon/performMgt/Test.java, src/main/resources/mappers/performMapper.xml
인사평가 동료평가 , 자기 평가 나누기 
문제 100문제 select 
동료평가는 동료 선택 가능 
아직 점수하는 중...ㅜ
확인 후 승인 부탁드립니다
=> test update

front-react/src/approve/ApproveRouter.js, front-react/src/approve/components/ApprCodeToText.js, front-react/src/approve/components/ApproveMenu.js, front-react/src/approve/pages/Approve.js, front-react/src/approve/pages/ApproveForm.js, front-react/src/approve/pages/ApproveLine.js, front-react/src/approve/pages/ApproverDocList.js, front-react/src/approve/pages/DocumentList.js, front-react/src/common/components/helpers/axios_helper.js, front-react/src/common/contexts/UserContext.js, src/main/java/com/spring/daon/approve/ApproveController.java, src/main/java/com/spring/daon/approve/ApproveMapper.java, src/main/java/com/spring/daon/approve/ApproveServiceImpl.java, src/main/java/com/spring/daon/login/config/UserAuthProvider.java, src/main/java/com/spring/daon/login/controller/LoginController.java, src/main/resources/mappers/approveMapper.xml
1. 전자결재 리스트 띄우기
2. 리프레시 토큰 갱신 오류 해결
=> approve list, refresh error resolve

src/main/resources/application.properties
=> application properties update

front-react/src/messenger/pages/MessengerChat.js, front-react/src/messenger/pages/MessengerPop.js, src/main/java/com/spring/daon/messenger/chat/ChatController.java, src/main/java/com/spring/daon/messenger/chat/ChatMapper.java, src/main/java/com/spring/daon/messenger/chat/ChatServiceImpl.java, src/main/resources/mappers/chatMapper.xml
로컬호스트 -> http://${window.location.hostname}:8081 경로 수정 테스트...
=> messenger Modify route

src/main/java/com/spring/daon/websocket/WebSocketEventListener.java, src/main/resources/application.properties
=> messenger Other seat notification function test

front-react/src/approve/components/ApproveLine.js
=> remove search

front-react/src/messenger/pages/MessengerPop.js
=> header add

front-react/src/messenger/MessengerRouter.js, src/main/resources/application.properties
=> news spelling modify

front-react/src/attendMgt/pages/AttendMgtLeftbar.js, front-react/src/schedule/pages/ScheduleLeftbar.js
=> schedule attend leftbar edit

front-react/src/attendMgt/css/AttendBoard.css, front-react/src/attendMgt/pages/AllVacationCreate.js, front-react/src/attendMgt/pages/AllVacationUsed.js, front-react/src/attendMgt/pages/DeptStatus.js, src/main/java/com/spring/daon/attendMgt/AttendMgtServiceImpl.java, src/main/java/com/spring/daon/schedule/ScheduleServiceImpl.java
근태 테이블 사용한 부분 css 이상해져서 수정
근태,일정 transactional 추가
=> attend table css edit transactional add

front-react/src/attendMgt/pages/AttendSettingLeft.js
=> workSchedule addModal close

front-react/src/attendMgt/components/AttendMgtTree.js, front-react/src/attendMgt/components/KibanaDashboard.js, front-react/src/attendMgt/pages/DeptStats.js, src/main/resources/application.properties
=> kibana main merge

front-react/src/messenger/pages/MessengerChat.js, src/main/resources/application.properties
=> messenger group chat list

front-react/src/attendMgt/pages/AttendSettingRight.js, front-react/src/attendMgt/pages/DeptStatus.js, front-react/src/schedule/pages/ScheduleAdd.js
=> attend edit

front-react/src/hrMgt/css/Registration.css, front-react/src/hrMgt/pages/EmployeeDetail.js, front-react/src/salary/pages/EmployeeSalaryList/generateSalaryPdf.js, src/main/java/com/spring/daon/salary/SalarySchedule/SalaryScheduleController.java, src/main/resources/application.properties
직원 등록 및 수정 화면 고정(오류해결)
급여대장 날짜 수정(오류해결)
=> employee update
